version: '2.4'

networks:
  fabric_network:
    name: fabric_network

volumes:
  peer_ledger:
  peer_chaincodes:
  peer_production:

services:
  peer.ORG.fabriczakat.local:
    container_name: peer.ORG.fabriczakat.local
    image: hyperledger/fabric-peer:2.5.10
    environment:
      - CORE_PEER_ID=peer.ORG.fabriczakat.local
      - CORE_PEER_ADDRESS=peer.ORG.fabriczakat.local:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer.ORG.fabriczakat.local:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.ORG.fabriczakat.local:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.ORG.fabriczakat.local:7051
      - CORE_PEER_LOCALMSPID=ORGMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /home/fabricadmin/fabric/organizations/peerOrganizations/ORG.fabriczakat.local/peers/peer.ORG.fabriczakat.local/msp:/etc/hyperledger/fabric/msp
      - /home/fabricadmin/fabric/organizations/peerOrganizations/ORG.fabriczakat.local/peers/peer.ORG.fabriczakat.local/tls:/etc/hyperledger/fabric/tls
      - peer_ledger:/var/hyperledger/production
      - peer_chaincodes:/opt/gopath/src/github.com/chaincode
      - peer_production:/var/hyperledger/production
    networks:
      - fabric_network
    extra_hosts:
      - "orderer.fabriczakat.local:10.104.0.3"  # Adjust this IP to your orderer's IP
      - "peer.org1.fabriczakat.local:10.104.0.2"
      - "peer.org2.fabriczakat.local:10.104.0.4"
