version: '3.8'

services:
  couchdb.org1.fabriczakat.local:
    container_name: couchdb.org1.fabriczakat.local
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - couchdb-org1:/opt/couchdb/data
    networks:
      - fabriczakat

  peer.org1.fabriczakat.local:
    container_name: peer.org1.fabriczakat.local
    image: hyperledger/fabric-peer:2.5.10
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabriczakat
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer.org1.fabriczakat.local
      - CORE_PEER_ADDRESS=peer.org1.fabriczakat.local:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer.org1.fabriczakat.local:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.org1.fabriczakat.local:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.org1.fabriczakat.local:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.fabriczakat.local:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      # Operations and metrics
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_METRICS_PROVIDER=prometheus
    depends_on:
      - couchdb.org1.fabriczakat.local
    ports:
      - "7051:7051"
      - "9443:9443"
    volumes:
      - /var/run/:/host/var/run/
      - $HOME/fabric/organizations/peerOrganizations/org1.fabriczakat.local/peers/peer.org1.fabriczakat.local:/etc/hyperledger/fabric
      - peer-org1:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      - fabriczakat

  cli.org1.fabriczakat.local:
    container_name: cli.org1.fabriczakat.local
    image: hyperledger/fabric-tools:2.5.10
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.org1.fabriczakat.local
      - CORE_PEER_ADDRESS=peer.org1.fabriczakat.local:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.fabriczakat.local/peers/peer.org1.fabriczakat.local/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.fabriczakat.local/peers/peer.org1.fabriczakat.local/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.fabriczakat.local/peers/peer.org1.fabriczakat.local/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.fabriczakat.local/users/Admin@org1.fabriczakat.local/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - $HOME/fabric/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
      - $HOME/fabric/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - $HOME/fabric/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - $HOME/fabric/config:/opt/gopath/src/github.com/hyperledger/fabric/peer/config
    networks:
      - fabriczakat

volumes:
  couchdb-org1:
  peer-org1:

networks:
  fabriczakat:
    external: true