#!/bin/bash
# Orderer CA

if [ -d "$HOME/fabric/fabric-ca-server-orderer" ]; then
    echo "Directory $HOME/fabric/fabric-ca-server-orderer already exists. Deleting."
    rm -rf $HOME/fabric/fabric-ca-server-orderer
fi
if ! [ -d "$HOME/fabric/fabric-ca-client" ]; then
    echo "⛔ Directory $HOME/fabric/fabric-ca-client does not exist. Exiting."
    exit 1
fi
if ! [ -f "$HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/signcerts/cert.pem" ] || ! [ -f "$HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/keystore/key.pem" ]; then
    echo "⛔ Orderer CA TLS cert or key not found in $HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp. Did script 04 run correctly?"
    exit 1
fi

cd $HOME/fabric

mkdir $HOME/fabric/fabric-ca-server-orderer
cp $HOME/bin/fabric-ca-server $HOME/fabric/fabric-ca-server-orderer
cd $HOME/fabric/fabric-ca-server-orderer

# IMPORTANT!
# The organization CA TLS cert and key pair that were generated by tls-ca server in the previous step must be copied to a new tls dir
echo "📄 Copying Orderer CA TLS cert and key..."
mkdir tls
cp $HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/signcerts/cert.pem tls && cp $HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/keystore/key.pem tls
if [ $? -ne 0 ]; then echo "⛔ Failed to copy Orderer CA TLS cert/key"; exit 1; fi
echo "✅ Orderer CA TLS cert and key copied successfully."

# the name doesnt have to be the same as the one in the tls-ca server
echo "🚀 Initializing Orderer CA server..."
./fabric-ca-server init -b btstrp-orderer:btstrp-ordererpw # bootstrap user and set FABRIC_CA_HOME here
if [ $? -ne 0 ]; then echo "⛔ Failed to initialize Orderer CA server"; exit 1; fi
echo "✅ Orderer CA server initialized successfully."