#!/bin/bash
# Orderer CA

if [ -d "$HOME/fabric/fabric-ca-server-orderer" ]; then
    echo "Directory $HOME/fabric/fabric-ca-server-orderer already exists. Deleting."
    rm -rf $HOME/fabric/fabric-ca-server-orderer
fi
if ! [ -d "$HOME/fabric/fabric-ca-client" ]; then
    echo "Directory $HOME/fabric/fabric-ca-client does not exist. Exiting."
    exit 1
fi

cd $HOME/fabric

mkdir $HOME/fabric/fabric-ca-server-orderer
cp $HOME/fabric/bin/fabric-ca-server $HOME/fabric/fabric-ca-server-orderer
cd $HOME/fabric/fabric-ca-server-orderer

# IMPORTANT!
# The organization CA TLS cert and key pair that were generated by tls-ca server in the previous step must be copied to a new tls dir
mkdir tls
cp $HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/signcerts/cert.pem tls && cp $HOME/fabric/fabric-ca-client/tls-ca/rcaadmin-orderer/msp/keystore/key.pem tls

# the name doesnt have to be the same as the one in the tls-ca server
./fabric-ca-server init -b rcaadmin-orderer:ordererpw # bootstrap user and set FABRIC_CA_HOME here