---
name: zakat-network
version: 1.0.0
description: Zakat Platform Fabric Network
client:
  organization: Org1MSP
  logging:
    level: info
  cryptoconfig:
    path: /home/fabricadmin/fabric/organizations
  credentialStore:
    path: /home/fabricadmin/fabric/platform/wallet
    cryptoStore:
      path: /home/fabricadmin/fabric/platform/wallet
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

channels:
  zakatchannel:
    orderers:
      - orderer.fabriczakat.local
    peers:
      peer.org1.fabriczakat.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer.org2.fabriczakat.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1MSP:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.fabriczakat.local/users/{username}@org1.fabriczakat.local/msp
    peers:
      - peer.org1.fabriczakat.local
  Org2MSP:
    mspid: Org2MSP
    cryptoPath: peerOrganizations/org2.fabriczakat.local/users/{username}@org2.fabriczakat.local/msp
    peers:
      - peer.org2.fabriczakat.local

orderers:
  orderer.fabriczakat.local:
    url: grpc://orderer.fabriczakat.local:7050
    grpcOptions:
      ssl-target-name-override: orderer.fabriczakat.local
      hostnameOverride: orderer.fabriczakat.local

peers:
  peer.org1.fabriczakat.local:
    url: grpc://peer.org1.fabriczakat.local:7051
    grpcOptions:
      ssl-target-name-override: peer.org1.fabriczakat.local
      hostnameOverride: peer.org1.fabriczakat.local
  peer.org2.fabriczakat.local:
    url: grpc://peer.org2.fabriczakat.local:7051
    grpcOptions:
      ssl-target-name-override: peer.org2.fabriczakat.local
      hostnameOverride: peer.org2.fabriczakat.local
